### PR TITLE
Fixes header end-padding, utf8 yaml, kaitai 0.7 compat

### LINKED ISSUE #2: Compiling "bgi_compiled_script.ksy" reports error
I just found your bgi scripts and read you article at kaitai.io ;) And was wondering if it's possible to decompile ._bp files? Since Kaitai Struct and Ruby is new to me, I assume I have to convert the .ksy files to .rb files with the "kaitai-struct-compiler". I works for "bgi_bytecode.ksy" but "bgi_compiled_script.ksy" tells me: 
`/seq/4: unable to find type 'bgi_bytecode', searching from bgi_compiled_script `
Or can you help me out with the ._bp files? Thanks a lot!

### PR DESCRIPTION
**Pull request by mchubby**
- [x] `u32` at file offset 0x1C is used to indicate header size, excluding magic "BurikoCompiledScriptVer1.00\x00". The `.body` struct is now lazy-loaded because it's an `instances` field instead of `seq`.

- [x] Assume input characters.yaml and meta.yaml are UTF-8 encoded (might be specific to Ruby 2.x inclusion of psych vs. 1.9's syck, haven't tested)

- [x] Fail with error message if .ksy templates were not compiled with `--debug`

- [x] Add `imports:` declaration in main ksy  (probably fixes #2)

### CODE REVIEW

**Comment by mchubby** [comment]
Added workaround instruction for issue #1

**Comment by mnakamura1337** [comment]
Thanks and sorry for such a huge delays with accepting these :)

File: bytecode/bgi_decompiler.rb [hunk 1]
```diff
@@ -52,6 +55,7 @@ def initialize(filename)
 
       @b = @bs.body
     rescue Kaitai::Struct::Stream::UnexpectedDataError => e
+      print e
```
Comment (mnakamura1337) [inline bytecode/bgi_decompiler.rb:58]: `p e` would be probably better here...
